name: ci
on:
  push:
    branches: [main, release/*, release, dummy-workflow]
  pull_request:
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.web.outputs.any_changed }}
      server: ${{ steps.server.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: changed files for web
        id: web
        uses: tj-actions/changed-files@v36
        with:
          files: |
            web
            .github/workflows/ci.yml
            .github/workflows/ci_web.yml
            .github/workflows/build_web.yml
            .github/workflows/deploy_web_nightly.yml

      - name: changed files for server
        id: server
        uses: tj-actions/changed-files@v36
        with:
          files: |
            server
            .github/workflows/ci.yml
            .github/workflows/ci_server.yml
            .github/workflows/build_server.yml
            .github/workflows/deploy_server_nightly.yml
  ci-web:
    needs: prepare
    if: needs.prepare.outputs.web == 'true'
    uses: ./.github/workflows/ci_web.yml
  ci-server:
    needs: prepare
    if: needs.prepare.outputs.server == 'true'
    uses: ./.github/workflows/ci_server.yml
  ci:
    runs-on: ubuntu-latest
    needs:
      - ci-web
      - ci-server
    if: '!failure()'
    steps:
      - run: echo OK
  ci-collect-info:
    needs: ci
    if: '!failure()'
    uses: ./.github/workflows/ci_collect_info.yml
    with:
      branch: ${{github.ref}}
  build-web:
    needs: 
      - ci
      - ci-web
      - ci-collect-info
    runs-on: ubuntu-latest
    if: ${{!failure()}}
    steps:
      - name: Dispatch Web Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build_web.yml
          inputs: '{
            "sha_short": "${{ needs.ci-collect-info.outputs.sha_short }}", 
            "new_tag": "${{ needs.ci-collect-info.outputs.new_tag }}", 
            "new_tag_short": "${{ needs.ci-collect-info.outputs.new_tag_short }}", 
            "name": "${{ needs.ci-collect-info.outputs.name }}"
            }'
  build-server:
    needs: 
      - ci
      - ci-server
      - ci-collect-info
    runs-on: ubuntu-latest
    if: ${{!failure()}}
    steps:
      - name: Dispatch Server Build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build_server.yml
          inputs: '{
            "sha_short": "${{ needs.ci-collect-info.outputs.sha_short }}", 
            "new_tag": "${{ needs.ci-collect-info.outputs.new_tag }}", 
            "new_tag_short": "${{ needs.ci-collect-info.outputs.new_tag_short }}", 
            "name": "${{ needs.ci-collect-info.outputs.name }}"
            }'