name: collect-info
on:
  workflow_call:
    # Map the workflow outputs to job outputs
    inputs:
      branch:
        description: 'Branch Name'
        required: true
        type: string
      
    outputs:
        sha_short: 
            value: ${{ jobs.info.outputs.sha_short }}
        new_tag: 
            value: ${{ jobs.info.outputs.new_tag }}
        new_tag_short: 
            value: ${{ jobs.info.outputs.new_tag_short }}
        name: 
            value: ${{ jobs.info.outputs.name }}

jobs:
    